version: "3"

services:
  database:
    image: postgres:15
    container_name: playgroundable-db
    networks:
      - playgroundable-net
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - ./migrations/create-database:/docker-entrypoint-initdb.d
    ports:
      - 35432:5432
    environment: 
      POSTGRES_PASSWORD: 123
  minio:
    image: quay.io/minio/minio:RELEASE.2023-03-24T21-41-23Z.fips
    container_name: playgroundable-minio
    command: server --address ":9002" --console-address ":9092" /data
    ports:
      - 9003:9003
      - 9093:9093
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 123123123
    volumes:
      - "minio-data:/var/lib/minio/data"
    networks:
      - playgroundable-net
networks:
  playgroundable-net:
    driver: bridge
volumes:
  postgres-data:
  minio-data:
